apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/gateway:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000  # Express listens on 5001
        env:
          - name: PORT
            value: "5000"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-credentials
                key: password
          - name: SESSION_SECRET
            value: "your-production-secret"  # Consider moving this into a secret as well
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # Internal port in the cluster
      targetPort: 5000 # Forwards to the container's port
