apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-app
  template:
    metadata:
      labels:
        app: event-app
    spec:
      containers:
      - name: event-app
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/event-app:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80   # NGINX listens on port 80 (per your Dockerfile)
        resources:
          requests:
            cpu: 126m
            memory: 256Mi
          limits:
            cpu: 256m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: event-app
spec:
  selector:
    app: event-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # External port to reach the service
      targetPort: 80    # Matches containerPort (NGINX)
