apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-app
  template:
    metadata:
      labels:
        app: event-app
    spec:
      containers:
      - name: event-app
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/event-app:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000    # The container listens on 3000
        env:
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 126m
            memory: 1024Mi
          limits:
            cpu: 256m
            memory: 2048Mi

---
apiVersion: v1
kind: Service
metadata:
  name: event-app
spec:
  selector:
    app: event-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80           # The external Service port
      targetPort: 3000   # Must match containerPort (3000)
