apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: $CONTAINER_REGISTRY_LOGIN_SERVER/backend:$VERSION
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5001
        env:
          - name: PORT
            value: "5001"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: my-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-db-credentials
                key: password
          - name: SESSION_SECRET
            value: "your-production-secret"  # Consider storing this in a secret as well!
        resources:
          requests:
            cpu: 126m
            memory: 126Mi
          limits:
            cpu: 256m
            memory: 256Mi
