name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows workflow to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js modules (gateway)
        uses: actions/cache@v3
        with:
          path: gateway/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('gateway/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (gateway)
        run: npm install
        working-directory: gateway

      - name: Cache Node.js modules (events-ms)
        uses: actions/cache@v3
        with:
          path: events-ms/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('events-ms/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (events-ms)
        run: npm install
        working-directory: events-ms

      - name: Run tests
        run: npm test
        working-directory: gateway
