name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0' # Or your Node.js version

      - name: Install dependencies
        run: |
          cd gateway
          npm install

      - name: Run tests
        run: |
          cd gateway
          npm test
